# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' cover_val
#' @param x A single integer.
#' @useDynLib geosampling
#' @importFrom Rcpp sourceCpp
cover_val <- function(x, size = 30L) {
    .Call('_geosampling_cover_val', PACKAGE = 'geosampling', x, size)
}

